<pre>version: &apos;3.9&apos;

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
    volumes:
      - ./db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always

  nextcloud:
    image: nextcloud:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      NEXTCLOUD_TRUSTED_DOMAINS: localhost
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./nextcloud_data:/var/www/html

  onlyoffice:
    image: onlyoffice/documentserver
    restart: always
    ports:
      - "8082:80"

  cron:
    image: nextcloud:fpm
    restart: always
    volumes:
      - ./nextcloud_data:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db_data:
  nextcloud_data: