version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8888:80"
    environment:
      WORDPRESS_DB_HOST: db:5432
      WORDPRESS_DB_USER: postgresql
      WORDPRESS_DB_PASSWORD: postgresql
      WORDPRESS_DB_NAME: postgresql
    volumes:
      - ./wordpress_data:/var/www/html

volumes:
  postgres_data:
  wordpress_data:
